/** ISO country dialing codes for phone country selector */
export const COUNTRY_DIAL_CODES = [
  { code: 'AF', dial: '+93', label: 'Afghanistan (+93)' },
  { code: 'AL', dial: '+355', label: 'Albania (+355)' },
  { code: 'DZ', dial: '+213', label: 'Algeria (+213)' },
  { code: 'AS', dial: '+1', label: 'American Samoa (+1)' },
  { code: 'AD', dial: '+376', label: 'Andorra (+376)' },
  { code: 'AO', dial: '+244', label: 'Angola (+244)' },
  { code: 'AI', dial: '+1', label: 'Anguilla (+1)' },
  { code: 'AG', dial: '+1', label: 'Antigua & Barbuda (+1)' },
  { code: 'AR', dial: '+54', label: 'Argentina (+54)' },
  { code: 'AM', dial: '+374', label: 'Armenia (+374)' },
  { code: 'AW', dial: '+297', label: 'Aruba (+297)' },
  { code: 'AU', dial: '+61', label: 'Australia (+61)' },
  { code: 'AT', dial: '+43', label: 'Austria (+43)' },
  { code: 'AZ', dial: '+994', label: 'Azerbaijan (+994)' },
  { code: 'BS', dial: '+1', label: 'Bahamas (+1)' },
  { code: 'BH', dial: '+973', label: 'Bahrain (+973)' },
  { code: 'BD', dial: '+880', label: 'Bangladesh (+880)' },
  { code: 'BB', dial: '+1', label: 'Barbados (+1)' },
  { code: 'BY', dial: '+375', label: 'Belarus (+375)' },
  { code: 'BE', dial: '+32', label: 'Belgium (+32)' },
  { code: 'BZ', dial: '+501', label: 'Belize (+501)' },
  { code: 'BJ', dial: '+229', label: 'Benin (+229)' },
  { code: 'BM', dial: '+1', label: 'Bermuda (+1)' },
  { code: 'BT', dial: '+975', label: 'Bhutan (+975)' },
  { code: 'BO', dial: '+591', label: 'Bolivia (+591)' },
  { code: 'BA', dial: '+387', label: 'Bosnia & Herzegovina (+387)' },
  { code: 'BW', dial: '+267', label: 'Botswana (+267)' },
  { code: 'BR', dial: '+55', label: 'Brazil (+55)' },
  { code: 'IO', dial: '+246', label: 'British Indian Ocean Territory (+246)' },
  { code: 'VG', dial: '+1', label: 'British Virgin Islands (+1)' },
  { code: 'BN', dial: '+673', label: 'Brunei (+673)' },
  { code: 'BG', dial: '+359', label: 'Bulgaria (+359)' },
  { code: 'BF', dial: '+226', label: 'Burkina Faso (+226)' },
  { code: 'BI', dial: '+257', label: 'Burundi (+257)' },
  { code: 'KH', dial: '+855', label: 'Cambodia (+855)' },
  { code: 'CM', dial: '+237', label: 'Cameroon (+237)' },
  { code: 'CA', dial: '+1', label: 'Canada (+1)' },
  { code: 'CV', dial: '+238', label: 'Cape Verde (+238)' },
  { code: 'KY', dial: '+1', label: 'Cayman Islands (+1)' },
  { code: 'CF', dial: '+236', label: 'Central African Republic (+236)' },
  { code: 'TD', dial: '+235', label: 'Chad (+235)' },
  { code: 'CL', dial: '+56', label: 'Chile (+56)' },
  { code: 'CN', dial: '+86', label: 'China (+86)' },
  { code: 'CX', dial: '+61', label: 'Christmas Island (+61)' },
  { code: 'CC', dial: '+61', label: 'Cocos Islands (+61)' },
  { code: 'CO', dial: '+57', label: 'Colombia (+57)' },
  { code: 'KM', dial: '+269', label: 'Comoros (+269)' },
  { code: 'CG', dial: '+242', label: 'Congo (+242)' },
  { code: 'CD', dial: '+243', label: 'Congo (DRC) (+243)' },
  { code: 'CK', dial: '+682', label: 'Cook Islands (+682)' },
  { code: 'CR', dial: '+506', label: 'Costa Rica (+506)' },
  { code: 'CI', dial: '+225', label: "Côte d'Ivoire (+225)" },
  { code: 'HR', dial: '+385', label: 'Croatia (+385)' },
  { code: 'CU', dial: '+53', label: 'Cuba (+53)' },
  { code: 'CW', dial: '+599', label: 'Curaçao (+599)' },
  { code: 'CY', dial: '+357', label: 'Cyprus (+357)' },
  { code: 'CZ', dial: '+420', label: 'Czech Republic (+420)' },
  { code: 'DK', dial: '+45', label: 'Denmark (+45)' },
  { code: 'DJ', dial: '+253', label: 'Djibouti (+253)' },
  { code: 'DM', dial: '+1', label: 'Dominica (+1)' },
  { code: 'DO', dial: '+1', label: 'Dominican Republic (+1)' },
  { code: 'EC', dial: '+593', label: 'Ecuador (+593)' },
  { code: 'EG', dial: '+20', label: 'Egypt (+20)' },
  { code: 'SV', dial: '+503', label: 'El Salvador (+503)' },
  { code: 'GQ', dial: '+240', label: 'Equatorial Guinea (+240)' },
  { code: 'ER', dial: '+291', label: 'Eritrea (+291)' },
  { code: 'EE', dial: '+372', label: 'Estonia (+372)' },
  { code: 'SZ', dial: '+268', label: 'Eswatini (+268)' },
  { code: 'ET', dial: '+251', label: 'Ethiopia (+251)' },
  { code: 'FK', dial: '+500', label: 'Falkland Islands (+500)' },
  { code: 'FO', dial: '+298', label: 'Faroe Islands (+298)' },
  { code: 'FJ', dial: '+679', label: 'Fiji (+679)' },
  { code: 'FI', dial: '+358', label: 'Finland (+358)' },
  { code: 'FR', dial: '+33', label: 'France (+33)' },
  { code: 'GF', dial: '+594', label: 'French Guiana (+594)' },
  { code: 'PF', dial: '+689', label: 'French Polynesia (+689)' },
  { code: 'GA', dial: '+241', label: 'Gabon (+241)' },
  { code: 'GM', dial: '+220', label: 'Gambia (+220)' },
  { code: 'GE', dial: '+995', label: 'Georgia (+995)' },
  { code: 'DE', dial: '+49', label: 'Germany (+49)' },
  { code: 'GH', dial: '+233', label: 'Ghana (+233)' },
  { code: 'GI', dial: '+350', label: 'Gibraltar (+350)' },
  { code: 'GR', dial: '+30', label: 'Greece (+30)' },
  { code: 'GL', dial: '+299', label: 'Greenland (+299)' },
  { code: 'GD', dial: '+1', label: 'Grenada (+1)' },
  { code: 'GP', dial: '+590', label: 'Guadeloupe (+590)' },
  { code: 'GU', dial: '+1', label: 'Guam (+1)' },
  { code: 'GT', dial: '+502', label: 'Guatemala (+502)' },
  { code: 'GG', dial: '+44', label: 'Guernsey (+44)' },
  { code: 'GN', dial: '+224', label: 'Guinea (+224)' },
  { code: 'GW', dial: '+245', label: 'Guinea-Bissau (+245)' },
  { code: 'GY', dial: '+592', label: 'Guyana (+592)' },
  { code: 'HT', dial: '+509', label: 'Haiti (+509)' },
  { code: 'HN', dial: '+504', label: 'Honduras (+504)' },
  { code: 'HK', dial: '+852', label: 'Hong Kong (+852)' },
  { code: 'HU', dial: '+36', label: 'Hungary (+36)' },
  { code: 'IS', dial: '+354', label: 'Iceland (+354)' },
  { code: 'IN', dial: '+91', label: 'India (+91)' },
  { code: 'ID', dial: '+62', label: 'Indonesia (+62)' },
  { code: 'IR', dial: '+98', label: 'Iran (+98)' },
  { code: 'IQ', dial: '+964', label: 'Iraq (+964)' },
  { code: 'IE', dial: '+353', label: 'Ireland (+353)' },
  { code: 'IM', dial: '+44', label: 'Isle of Man (+44)' },
  { code: 'IL', dial: '+972', label: 'Israel (+972)' },
  { code: 'IT', dial: '+39', label: 'Italy (+39)' },
  { code: 'JM', dial: '+1', label: 'Jamaica (+1)' },
  { code: 'JP', dial: '+81', label: 'Japan (+81)' },
  { code: 'JE', dial: '+44', label: 'Jersey (+44)' },
  { code: 'JO', dial: '+962', label: 'Jordan (+962)' },
  { code: 'KZ', dial: '+7', label: 'Kazakhstan (+7)' },
  { code: 'KE', dial: '+254', label: 'Kenya (+254)' },
  { code: 'KI', dial: '+686', label: 'Kiribati (+686)' },
  { code: 'XK', dial: '+383', label: 'Kosovo (+383)' },
  { code: 'KW', dial: '+965', label: 'Kuwait (+965)' },
  { code: 'KG', dial: '+996', label: 'Kyrgyzstan (+996)' },
  { code: 'LA', dial: '+856', label: 'Laos (+856)' },
  { code: 'LV', dial: '+371', label: 'Latvia (+371)' },
  { code: 'LB', dial: '+961', label: 'Lebanon (+961)' },
  { code: 'LS', dial: '+266', label: 'Lesotho (+266)' },
  { code: 'LR', dial: '+231', label: 'Liberia (+231)' },
  { code: 'LY', dial: '+218', label: 'Libya (+218)' },
  { code: 'LI', dial: '+423', label: 'Liechtenstein (+423)' },
  { code: 'LT', dial: '+370', label: 'Lithuania (+370)' },
  { code: 'LU', dial: '+352', label: 'Luxembourg (+352)' },
  { code: 'MO', dial: '+853', label: 'Macao (+853)' },
  { code: 'MG', dial: '+261', label: 'Madagascar (+261)' },
  { code: 'MW', dial: '+265', label: 'Malawi (+265)' },
  { code: 'MY', dial: '+60', label: 'Malaysia (+60)' },
  { code: 'MV', dial: '+960', label: 'Maldives (+960)' },
  { code: 'ML', dial: '+223', label: 'Mali (+223)' },
  { code: 'MT', dial: '+356', label: 'Malta (+356)' },
  { code: 'MH', dial: '+692', label: 'Marshall Islands (+692)' },
  { code: 'MQ', dial: '+596', label: 'Martinique (+596)' },
  { code: 'MR', dial: '+222', label: 'Mauritania (+222)' },
  { code: 'MU', dial: '+230', label: 'Mauritius (+230)' },
  { code: 'YT', dial: '+262', label: 'Mayotte (+262)' },
  { code: 'MX', dial: '+52', label: 'Mexico (+52)' },
  { code: 'FM', dial: '+691', label: 'Micronesia (+691)' },
  { code: 'MD', dial: '+373', label: 'Moldova (+373)' },
  { code: 'MC', dial: '+377', label: 'Monaco (+377)' },
  { code: 'MN', dial: '+976', label: 'Mongolia (+976)' },
  { code: 'ME', dial: '+382', label: 'Montenegro (+382)' },
  { code: 'MS', dial: '+1', label: 'Montserrat (+1)' },
  { code: 'MA', dial: '+212', label: 'Morocco (+212)' },
  { code: 'MZ', dial: '+258', label: 'Mozambique (+258)' },
  { code: 'MM', dial: '+95', label: 'Myanmar (+95)' },
  { code: 'NA', dial: '+264', label: 'Namibia (+264)' },
  { code: 'NR', dial: '+674', label: 'Nauru (+674)' },
  { code: 'NP', dial: '+977', label: 'Nepal (+977)' },
  { code: 'NL', dial: '+31', label: 'Netherlands (+31)' },
  { code: 'NC', dial: '+687', label: 'New Caledonia (+687)' },
  { code: 'NZ', dial: '+64', label: 'New Zealand (+64)' },
  { code: 'NI', dial: '+505', label: 'Nicaragua (+505)' },
  { code: 'NE', dial: '+227', label: 'Niger (+227)' },
  { code: 'NG', dial: '+234', label: 'Nigeria (+234)' },
  { code: 'NU', dial: '+683', label: 'Niue (+683)' },
  { code: 'NF', dial: '+672', label: 'Norfolk Island (+672)' },
  { code: 'KP', dial: '+850', label: 'North Korea (+850)' },
  { code: 'MK', dial: '+389', label: 'North Macedonia (+389)' },
  { code: 'MP', dial: '+1', label: 'Northern Mariana Islands (+1)' },
  { code: 'NO', dial: '+47', label: 'Norway (+47)' },
  { code: 'OM', dial: '+968', label: 'Oman (+968)' },
  { code: 'PK', dial: '+92', label: 'Pakistan (+92)' },
  { code: 'PW', dial: '+680', label: 'Palau (+680)' },
  { code: 'PS', dial: '+970', label: 'Palestine (+970)' },
  { code: 'PA', dial: '+507', label: 'Panama (+507)' },
  { code: 'PG', dial: '+675', label: 'Papua New Guinea (+675)' },
  { code: 'PY', dial: '+595', label: 'Paraguay (+595)' },
  { code: 'PE', dial: '+51', label: 'Peru (+51)' },
  { code: 'PH', dial: '+63', label: 'Philippines (+63)' },
  { code: 'PL', dial: '+48', label: 'Poland (+48)' },
  { code: 'PT', dial: '+351', label: 'Portugal (+351)' },
  { code: 'PR', dial: '+1', label: 'Puerto Rico (+1)' },
  { code: 'QA', dial: '+974', label: 'Qatar (+974)' },
  { code: 'RE', dial: '+262', label: 'Réunion (+262)' },
  { code: 'RO', dial: '+40', label: 'Romania (+40)' },
  { code: 'RU', dial: '+7', label: 'Russia (+7)' },
  { code: 'RW', dial: '+250', label: 'Rwanda (+250)' },
  { code: 'BL', dial: '+590', label: 'Saint Barthélemy (+590)' },
  { code: 'SH', dial: '+290', label: 'Saint Helena (+290)' },
  { code: 'KN', dial: '+1', label: 'Saint Kitts & Nevis (+1)' },
  { code: 'LC', dial: '+1', label: 'Saint Lucia (+1)' },
  { code: 'MF', dial: '+590', label: 'Saint Martin (+590)' },
  { code: 'PM', dial: '+508', label: 'Saint Pierre & Miquelon (+508)' },
  { code: 'VC', dial: '+1', label: 'Saint Vincent & Grenadines (+1)' },
  { code: 'WS', dial: '+685', label: 'Samoa (+685)' },
  { code: 'SM', dial: '+378', label: 'San Marino (+378)' },
  { code: 'ST', dial: '+239', label: 'São Tomé & Príncipe (+239)' },
  { code: 'SA', dial: '+966', label: 'Saudi Arabia (+966)' },
  { code: 'SN', dial: '+221', label: 'Senegal (+221)' },
  { code: 'RS', dial: '+381', label: 'Serbia (+381)' },
  { code: 'SC', dial: '+248', label: 'Seychelles (+248)' },
  { code: 'SL', dial: '+232', label: 'Sierra Leone (+232)' },
  { code: 'SG', dial: '+65', label: 'Singapore (+65)' },
  { code: 'SX', dial: '+1', label: 'Sint Maarten (+1)' },
  { code: 'SK', dial: '+421', label: 'Slovakia (+421)' },
  { code: 'SI', dial: '+386', label: 'Slovenia (+386)' },
  { code: 'SB', dial: '+677', label: 'Solomon Islands (+677)' },
  { code: 'SO', dial: '+252', label: 'Somalia (+252)' },
  { code: 'ZA', dial: '+27', label: 'South Africa (+27)' },
  { code: 'KR', dial: '+82', label: 'South Korea (+82)' },
  { code: 'SS', dial: '+211', label: 'South Sudan (+211)' },
  { code: 'ES', dial: '+34', label: 'Spain (+34)' },
  { code: 'LK', dial: '+94', label: 'Sri Lanka (+94)' },
  { code: 'SD', dial: '+249', label: 'Sudan (+249)' },
  { code: 'SR', dial: '+597', label: 'Suriname (+597)' },
  { code: 'SE', dial: '+46', label: 'Sweden (+46)' },
  { code: 'CH', dial: '+41', label: 'Switzerland (+41)' },
  { code: 'SY', dial: '+963', label: 'Syria (+963)' },
  { code: 'TW', dial: '+886', label: 'Taiwan (+886)' },
  { code: 'TJ', dial: '+992', label: 'Tajikistan (+992)' },
  { code: 'TZ', dial: '+255', label: 'Tanzania (+255)' },
  { code: 'TH', dial: '+66', label: 'Thailand (+66)' },
  { code: 'TL', dial: '+670', label: 'Timor-Leste (+670)' },
  { code: 'TG', dial: '+228', label: 'Togo (+228)' },
  { code: 'TK', dial: '+690', label: 'Tokelau (+690)' },
  { code: 'TO', dial: '+676', label: 'Tonga (+676)' },
  { code: 'TT', dial: '+1', label: 'Trinidad & Tobago (+1)' },
  { code: 'TN', dial: '+216', label: 'Tunisia (+216)' },
  { code: 'TR', dial: '+90', label: 'Turkey (+90)' },
  { code: 'TM', dial: '+993', label: 'Turkmenistan (+993)' },
  { code: 'TC', dial: '+1', label: 'Turks & Caicos (+1)' },
  { code: 'TV', dial: '+688', label: 'Tuvalu (+688)' },
  { code: 'VI', dial: '+1', label: 'U.S. Virgin Islands (+1)' },
  { code: 'UG', dial: '+256', label: 'Uganda (+256)' },
  { code: 'UA', dial: '+380', label: 'Ukraine (+380)' },
  { code: 'AE', dial: '+971', label: 'United Arab Emirates (+971)' },
  { code: 'GB', dial: '+44', label: 'United Kingdom (+44)' },
  { code: 'US', dial: '+1', label: 'United States (+1)' },
  { code: 'UY', dial: '+598', label: 'Uruguay (+598)' },
  { code: 'UZ', dial: '+998', label: 'Uzbekistan (+998)' },
  { code: 'VU', dial: '+678', label: 'Vanuatu (+678)' },
  { code: 'VA', dial: '+39', label: 'Vatican City (+39)' },
  { code: 'VE', dial: '+58', label: 'Venezuela (+58)' },
  { code: 'VN', dial: '+84', label: 'Vietnam (+84)' },
  { code: 'WF', dial: '+681', label: 'Wallis & Futuna (+681)' },
  { code: 'YE', dial: '+967', label: 'Yemen (+967)' },
  { code: 'ZM', dial: '+260', label: 'Zambia (+260)' },
  { code: 'ZW', dial: '+263', label: 'Zimbabwe (+263)' },
]

/** Prefer unique option values when dial codes collide (e.g. +1). */
export const COUNTRY_SELECT_OPTIONS = COUNTRY_DIAL_CODES.map((c) => ({
  value: `${c.code}:${c.dial}`,
  label: c.label,
  dial: c.dial,
  code: c.code,
}))

export function dialFromCountryValue(value) {
  if (!value) return '+94'
  const parts = String(value).split(':')
  return parts[1] || parts[0] || '+94'
}
